In [ ]:
import pandas as pd
from database import postgres_connection
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RandomizedSearchCV
from catboost import CatBoostClassifier
from category_encoders import MEstimateEncoder
import pickle

In [2]:
query_users = "SELECT * FROM public.user_data"
df_users = pd.read_sql(query_users, con=postgres_connection())

C:\Users\ilyap\AppData\Local\Temp\ipykernel_41716\2029752923.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_users = pd.read_sql(query_users, con=postgres_connection())

In [3]:
query_posts = "SELECT * FROM public.post_text_df"
df_posts = pd.read_sql(query_posts, con=postgres_connection())

C:\Users\ilyap\AppData\Local\Temp\ipykernel_41716\243597251.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_posts = pd.read_sql(query_posts, con=postgres_connection())

In [4]:
query_user_aggs = """
SELECT 
    user_id,
    COUNT(*) as n_views,
    SUM(target) as n_likes,
    MAX(timestamp) as last_seen_at
FROM public.feed_data
WHERE action = 'view'
GROUP BY user_id
"""
df_user_aggs = pd.read_sql(query_user_aggs, con=postgres_connection())
df_user_aggs['like_rate'] = df_user_aggs['n_likes'] / df_user_aggs['n_views']

query_post_aggs = """
SELECT 
    post_id,
    COUNT(*) as post_views,
    SUM(target) as post_likes
FROM public.feed_data
WHERE action = 'view'
GROUP BY post_id
"""
df_post_aggs = pd.read_sql(query_post_aggs, con=postgres_connection())
df_post_aggs['post_ctr'] = df_post_aggs['post_likes'] / (df_post_aggs['post_views'] + 10)

query_feed_sample = """
SELECT timestamp, user_id, post_id, target
FROM public.feed_data
WHERE action = 'view' AND user_id % 10 = 0
"""
df_feed = pd.read_sql(query_feed_sample, con=postgres_connection())

C:\Users\ilyap\AppData\Local\Temp\ipykernel_41716\1997449724.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_user_aggs = pd.read_sql(query_user_aggs, con=postgres_connection())
C:\Users\ilyap\AppData\Local\Temp\ipykernel_41716\1997449724.py:23: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_post_aggs = pd.read_sql(query_post_aggs, con=postgres_connection())
C:\Users\ilyap\AppData\Local\Temp\ipykernel_41716\1997449724.py:31: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_feed = pd.read_sql(query_feed_sample, con=postgres_connection())

In [5]:
df_feed

                  timestamp  user_id  post_id  target
0       2021-10-03 08:57:57    22710     2607       0
1       2021-10-03 09:00:37    22710      950       0
2       2021-10-03 09:01:58    22710     4233       0
3       2021-10-03 09:04:48    22710     1017       0
4       2021-10-03 09:07:09    22710     1161       0
...                     ...      ...      ...     ...
6881573 2021-12-16 09:07:54    66340     5313       0
6881574 2021-12-16 09:08:49    66340     5820       0
6881575 2021-12-16 09:09:39    66340      474       0
6881576 2021-12-16 09:12:20    66340     6122       0
6881577 2021-12-16 09:13:43    66340     4470       0

[6881578 rows x 4 columns]

In [6]:
df_users

,user_id,gender,age,country,city,exp_group,os,source
0,200,1,34,Russia,Degtyarsk,3,Android,ads
1,201,0,37,Russia,Abakan,0,Android,ads
2,202,1,17,Russia,Smolensk,4,Android,ads
3,203,0,18,Russia,Moscow,1,iOS,ads
4,204,0,36,Russia,Anzhero-Sudzhensk,3,Android,ads
...,...,...,...,...,...,...,...,...
163200,168548,0,36,Russia,Kaliningrad,4,Android,organic
163201,168549,0,18,Russia,Tula,2,Android,organic
163202,168550,1,41,Russia,Yekaterinburg,4,Android,organic
163203,168551,0,38,Russia,Moscow,3,iOS,organic
163204,168552,1,16,Russia,Ivanteyevka,4,Android,organic

In [7]:
df_posts

      post_id                                               text     topic
0           1  UK economy facing major risks\n\nThe UK manufa...  business
1           2  Aids and climate top Davos agenda\n\nClimate c...  business
2           3  Asian quake hits European shares\n\nShares in ...  business
3           4  India power shares jump on debut\n\nShares in ...  business
4           5  Lacroix label bought by US firm\n\nLuxury good...  business
...       ...                                                ...       ...
7018     7315  OK, I would not normally watch a Farrelly brot...     movie
7019     7316  I give this movie 2 stars purely because of it...     movie
7020     7317  I cant believe this film was allowed to be mad...     movie
7021     7318  The version I saw of this film was the Blockbu...     movie
7022     7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [8]:
df_feed['hour'] = df_feed['timestamp'].dt.hour
df_feed['dayofweek'] = df_feed['timestamp'].dt.dayofweek
df_feed['is_weekend'] = df_feed['dayofweek'].isin([5,6]).astype(int)

In [10]:
split_date = df_feed['timestamp'].quantile(0.8)

df_history = df_feed[df_feed['timestamp'] < split_date].copy()
df_train_period = df_feed[df_feed['timestamp'] >= split_date].copy()

df_users_prof = pd.merge(df_users, df_user_aggs, on='user_id', how='inner')

df_train_period = df_train_period.sort_values(['user_id', 'timestamp'])
df_train_period['last_action'] = df_train_period.groupby('user_id')['timestamp'].diff()
df_train_period['hours_of_last_action'] = df_train_period['last_action'].dt.total_seconds() / 3600

df_train_period = df_train_period.merge(df_users_prof[['user_id', 'last_seen_at']], on='user_id', how='left')
first_event_mask = df_train_period['last_action'].isna()
df_train_period.loc[first_event_mask, 'hours_of_last_action'] = (
    (df_train_period.loc[first_event_mask, 'timestamp'] - df_train_period.loc[first_event_mask, 'last_seen_at']).dt.total_seconds() / 3600
)

df_train_period = df_train_period.drop(columns=['last_action', 'last_seen_at'])

In [11]:
mte_cat_cols = ['country', 'city']

ohe_cat_cols = [col for col in df_users_prof.columns if df_users_prof[col].nunique() <= 5 and col not in mte_cat_cols]

ohe_cat_cols.append('topic')

In [12]:
ohe_cat_cols

['gender', 'exp_group', 'os', 'source', 'topic']

In [13]:
df_posts['text_len'] = df_posts['text'].str.len()
df_posts['text_words'] = df_posts['text'].str.split().str.len()

df_posts = pd.merge(df_posts, df_post_aggs[['post_id', 'post_ctr']], on='post_id', how='left')
df_posts['post_ctr'] = df_posts['post_ctr'].fillna(0)

df_posts.head()

,post_id,text,topic,text_len,text_words,post_ctr
0,1,UK economy facing major risks\n\nThe UK manufa...,business,1967,324,0.125264
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,2701,448,0.084877
2,3,Asian quake hits European shares\n\nShares in ...,business,3408,546,0.133223
3,4,India power shares jump on debut\n\nShares in ...,business,1026,173,0.143364
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,889,150,0.134179

In [14]:
df_final = pd.merge(df_train_period, df_users_prof, on='user_id', how='left')
df_final = pd.merge(df_final, df_posts, on='post_id', how='left')

In [15]:
df_final

,timestamp,user_id,post_id,target,hour,dayofweek,is_weekend,hours_of_last_action,gender,age,...,source,n_views,n_likes,last_seen_at,like_rate,text,topic,text_len,text_words,post_ctr
0,2021-12-13 08:14:54,200,1198,1,8,0,0,-391.168056,1,34,...,ads,358,43,2021-12-29 15:24:59,0.120112,UK helps raped Rwandan women\n\nBritain is to ...,politics,1365,226,0.093074
1,2021-12-13 08:16:23,200,7143,1,8,0,0,0.024722,1,34,...,ads,358,43,2021-12-29 15:24:59,0.120112,Heartland was in production about the same tim...,movie,660,111,0.104444
2,2021-12-13 08:18:56,200,681,0,8,0,0,0.042500,1,34,...,ads,358,43,2021-12-29 15:24:59,0.120112,Poppins musical gets flying start\n\nThe stage...,entertainment,1137,179,0.101675
3,2021-12-13 08:19:39,200,3447,0,8,0,0,0.011944,1,34,...,ads,358,43,2021-12-29 15:24:59,0.120112,#NSTworld #NKorea declares emergency over 1st ...,covid,95,10,0.107989
4,2021-12-13 08:22:37,200,7042,0,8,0,0,0.049444,1,34,...,ads,358,43,2021-12-29 15:24:59,0.120112,"The Brothers Quay are directors, judging by co...",movie,756,124,0.156569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1376312,2021-12-15 11:03:21,168550,3996,0,11,2,0,0.008056,1,41,...,organic,369,38,2021-12-15 11:09:36,0.102981,Right Now On Fired Up Smackdown Update #Smackd...,covid,132,14,0.094135
1376313,2021-12-15 11:05:32,168550,173,0,11,2,0,0.036389,1,41,...,organic,369,38,2021-12-15 11:09:36,0.102981,House prices rebound says Halifax\n\nUK house ...,business,2842,492,0.124797
1376314,2021-12-15 11:08:02,168550,3762,0,11,2,0,0.041667,1,41,...,organic,369,38,2021-12-15 11:09:36,0.102981,Really good graphic from @jacquesmarcoux today...,covid,140,20,0.153657
1376315,2021-12-15 11:08:32,168550,1568,0,11,2,0,0.008333,1,41,...,organic,369,38,2021-12-15 11:09:36,0.102981,Arnesen denies rift with Santini\n\nTottenham ...,sport,2283,403,0.158063
1376316,2021-12-15 11:09:36,168550,4252,0,11,2,0,0.017778,1,41,...,organic,369,38,2021-12-15 11:09:36,0.102981,This is one lowly film. It has no real plot. W...,movie,982,186,0.158011

In [16]:
df_final = df_final.sort_values('timestamp')

X = df_final.drop(columns=['target', 'timestamp', 'text', 'last_seen_at'], axis=1)
y = df_final['target']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, shuffle=False
)

print(X_train.columns.tolist())

['user_id', 'post_id', 'hour', 'dayofweek', 'is_weekend', 'hours_of_last_action', 'gender', 'age', 'country', 'city', 'exp_group', 'os', 'source', 'n_views', 'n_likes', 'like_rate', 'topic', 'text_len', 'text_words', 'post_ctr']

In [17]:
preprocessor = ColumnTransformer(
    transformers=[
        ('ohe', OneHotEncoder(handle_unknown='ignore'), ohe_cat_cols),
        ('mte', MEstimateEncoder(cols=mte_cat_cols, m=10.0), mte_cat_cols)
    ],
    remainder='passthrough'
)
pipe = Pipeline([
    ('preprocessor', preprocessor),
    ('model', CatBoostClassifier(
        iterations=300,
        early_stopping_rounds=50,))
    ])

param_grid = {
    'model__depth': [4, 6, 8, 10],
    'model__learning_rate': [0.01, 0.03, 0.05, 0.1],
    'model__l2_leaf_reg': [3, 10, 30],
    'model__bagging_temperature': [0.5, 1.0],
    'model__random_strength': [1, 3],
}

search = RandomizedSearchCV(
                      estimator=pipe, 
                      param_distributions=param_grid,
                      n_iter=15,
                      cv=2,
                      scoring='roc_auc',
                      n_jobs=1,
                      verbose=1,
                      random_state=42
                      )

In [18]:
search.fit(X_train, y_train)

Fitting 2 folds for each of 15 candidates, totalling 30 fits
0:	learn: 0.6582268	total: 137ms	remaining: 41s
1:	learn: 0.6276559	total: 207ms	remaining: 30.9s
2:	learn: 0.6021838	total: 268ms	remaining: 26.6s
3:	learn: 0.5782445	total: 338ms	remaining: 25s
4:	learn: 0.5562518	total: 414ms	remaining: 24.4s
5:	learn: 0.5372863	total: 478ms	remaining: 23.4s
6:	learn: 0.5206898	total: 547ms	remaining: 22.9s
7:	learn: 0.5069586	total: 616ms	remaining: 22.5s
8:	learn: 0.4938129	total: 677ms	remaining: 21.9s
9:	learn: 0.4821758	total: 752ms	remaining: 21.8s
10:	learn: 0.4706456	total: 827ms	remaining: 21.7s
11:	learn: 0.4614549	total: 895ms	remaining: 21.5s
12:	learn: 0.4530834	total: 951ms	remaining: 21s
13:	learn: 0.4456060	total: 1.02s	remaining: 20.8s
14:	learn: 0.4390694	total: 1.09s	remaining: 20.7s
15:	learn: 0.4335009	total: 1.16s	remaining: 20.6s
16:	learn: 0.4282728	total: 1.24s	remaining: 20.6s
17:	learn: 0.4231210	total: 1.3s	remaining: 20.3s
18:	learn: 0.4191779	total: 1.36s	remaining: 20.2s
19:	learn: 0.4148668	total: 1.43s	remaining: 20s
20:	learn: 0.4112799	total: 1.5s	remaining: 20s
21:	learn: 0.4084571	total: 1.56s	remaining: 19.7s
22:	learn: 0.4058991	total: 1.64s	remaining: 19.8s
23:	learn: 0.4038552	total: 1.69s	remaining: 19.5s
24:	learn: 0.4009303	total: 1.76s	remaining: 19.4s
25:	learn: 0.3991907	total: 1.86s	remaining: 19.6s
26:	learn: 0.3973871	total: 1.92s	remaining: 19.4s
27:	learn: 0.3958086	total: 1.97s	remaining: 19.2s
28:	learn: 0.3944767	total: 2.04s	remaining: 19s
29:	learn: 0.3930126	total: 2.1s	remaining: 18.9s
30:	learn: 0.3918965	total: 2.17s	remaining: 18.8s
31:	learn: 0.3908793	total: 2.24s	remaining: 18.8s
32:	learn: 0.3894193	total: 2.31s	remaining: 18.7s
33:	learn: 0.3880788	total: 2.39s	remaining: 18.7s
34:	learn: 0.3868052	total: 2.49s	remaining: 18.8s
35:	learn: 0.3852541	total: 2.63s	remaining: 19.3s
36:	learn: 0.3845693	total: 2.71s	remaining: 19.3s
37:	learn: 0.3839992	total: 2.8s	remaining: 19.3s
38:	learn: 0.3834907	total: 2.87s	remaining: 19.2s
39:	learn: 0.3828749	total: 2.94s	remaining: 19.1s
40:	learn: 0.3824628	total: 3.02s	remaining: 19.1s
41:	learn: 0.3821714	total: 3.06s	remaining: 18.8s
42:	learn: 0.3818830	total: 3.11s	remaining: 18.6s
43:	learn: 0.3815883	total: 3.16s	remaining: 18.4s
44:	learn: 0.3813173	total: 3.21s	remaining: 18.2s
45:	learn: 0.3810165	total: 3.25s	remaining: 18s
46:	learn: 0.3805188	total: 3.3s	remaining: 17.7s
47:	learn: 0.3802761	total: 3.34s	remaining: 17.5s
48:	learn: 0.3800554	total: 3.39s	remaining: 17.4s
49:	learn: 0.3794942	total: 3.43s	remaining: 17.2s
50:	learn: 0.3788909	total: 3.48s	remaining: 17s
51:	learn: 0.3783076	total: 3.52s	remaining: 16.8s
52:	learn: 0.3781871	total: 3.56s	remaining: 16.6s
53:	learn: 0.3780384	total: 3.6s	remaining: 16.4s
54:	learn: 0.3777532	total: 3.65s	remaining: 16.3s
55:	learn: 0.3776271	total: 3.69s	remaining: 16.1s
56:	learn: 0.3774512	total: 3.75s	remaining: 16s
57:	learn: 0.3773460	total: 3.81s	remaining: 15.9s
58:	learn: 0.3771759	total: 3.86s	remaining: 15.8s
59:	learn: 0.3769826	total: 3.9s	remaining: 15.6s
60:	learn: 0.3767764	total: 3.95s	remaining: 15.5s
61:	learn: 0.3766810	total: 4s	remaining: 15.4s
62:	learn: 0.3765739	total: 4.05s	remaining: 15.3s
63:	learn: 0.3764895	total: 4.1s	remaining: 15.1s
64:	learn: 0.3760774	total: 4.15s	remaining: 15s
65:	learn: 0.3759899	total: 4.19s	remaining: 14.9s
66:	learn: 0.3759233	total: 4.24s	remaining: 14.7s
67:	learn: 0.3756584	total: 4.29s	remaining: 14.6s
68:	learn: 0.3752645	total: 4.34s	remaining: 14.5s
69:	learn: 0.3751627	total: 4.38s	remaining: 14.4s
70:	learn: 0.3750997	total: 4.43s	remaining: 14.3s
71:	learn: 0.3750636	total: 4.48s	remaining: 14.2s
72:	learn: 0.3750174	total: 4.53s	remaining: 14.1s
73:	learn: 0.3748035	total: 4.58s	remaining: 14s
74:	learn: 0.3746974	total: 4.62s	remaining: 13.9s
75:	learn: 0.3746558	total: 4.66s	remaining: 13.7s
76:	learn: 0.3746056	total: 4.7s	remaining: 13.6s
77:	learn: 0.3744174	total: 4.76s	remaining: 13.5s
78:	learn: 0.3741770	total: 4.8s	remaining: 13.4s
79:	learn: 0.3741452	total: 4.85s	remaining: 13.3s
80:	learn: 0.3741062	total: 4.91s	remaining: 13.3s
81:	learn: 0.3740829	total: 4.96s	remaining: 13.2s
82:	learn: 0.3740600	total: 5.01s	remaining: 13.1s
83:	learn: 0.3739141	total: 5.05s	remaining: 13s
84:	learn: 0.3738103	total: 5.09s	remaining: 12.9s
85:	learn: 0.3737740	total: 5.14s	remaining: 12.8s
86:	learn: 0.3735864	total: 5.19s	remaining: 12.7s
87:	learn: 0.3732972	total: 5.24s	remaining: 12.6s
88:	learn: 0.3732279	total: 5.29s	remaining: 12.5s
89:	learn: 0.3731983	total: 5.32s	remaining: 12.4s
90:	learn: 0.3730231	total: 5.36s	remaining: 12.3s
91:	learn: 0.3730066	total: 5.41s	remaining: 12.2s
92:	learn: 0.3729730	total: 5.45s	remaining: 12.1s
93:	learn: 0.3729542	total: 5.5s	remaining: 12.1s
94:	learn: 0.3728250	total: 5.54s	remaining: 12s
95:	learn: 0.3727919	total: 5.58s	remaining: 11.9s
96:	learn: 0.3727669	total: 5.62s	remaining: 11.8s
97:	learn: 0.3725893	total: 5.67s	remaining: 11.7s
98:	learn: 0.3725772	total: 5.71s	remaining: 11.6s
99:	learn: 0.3725647	total: 5.75s	remaining: 11.5s
100:	learn: 0.3725464	total: 5.81s	remaining: 11.4s
101:	learn: 0.3725217	total: 5.85s	remaining: 11.4s
102:	learn: 0.3725094	total: 5.9s	remaining: 11.3s
103:	learn: 0.3724918	total: 5.95s	remaining: 11.2s
104:	learn: 0.3724683	total: 6.01s	remaining: 11.2s
105:	learn: 0.3724495	total: 6.06s	remaining: 11.1s
106:	learn: 0.3724306	total: 6.13s	remaining: 11.1s
107:	learn: 0.3723049	total: 6.19s	remaining: 11s
108:	learn: 0.3722817	total: 6.25s	remaining: 10.9s
109:	learn: 0.3722645	total: 6.3s	remaining: 10.9s
110:	learn: 0.3722530	total: 6.35s	remaining: 10.8s
111:	learn: 0.3721941	total: 6.41s	remaining: 10.8s
112:	learn: 0.3721449	total: 6.46s	remaining: 10.7s
113:	learn: 0.3721296	total: 6.51s	remaining: 10.6s
114:	learn: 0.3720001	total: 6.57s	remaining: 10.6s
115:	learn: 0.3718465	total: 6.63s	remaining: 10.5s
116:	learn: 0.3718299	total: 6.69s	remaining: 10.5s
117:	learn: 0.3718228	total: 6.74s	remaining: 10.4s
118:	learn: 0.3717663	total: 6.8s	remaining: 10.3s
119:	learn: 0.3716275	total: 6.85s	remaining: 10.3s
120:	learn: 0.3716118	total: 6.91s	remaining: 10.2s
121:	learn: 0.3715093	total: 6.97s	remaining: 10.2s
122:	learn: 0.3714909	total: 7.03s	remaining: 10.1s
123:	learn: 0.3714838	total: 7.08s	remaining: 10.1s
124:	learn: 0.3714718	total: 7.13s	remaining: 9.99s
125:	learn: 0.3713832	total: 7.18s	remaining: 9.92s
126:	learn: 0.3713698	total: 7.23s	remaining: 9.85s
127:	learn: 0.3711936	total: 7.28s	remaining: 9.79s
128:	learn: 0.3711481	total: 7.33s	remaining: 9.72s
129:	learn: 0.3711308	total: 7.38s	remaining: 9.66s
130:	learn: 0.3711003	total: 7.44s	remaining: 9.6s
131:	learn: 0.3710861	total: 7.5s	remaining: 9.54s
132:	learn: 0.3710190	total: 7.54s	remaining: 9.47s
133:	learn: 0.3710011	total: 7.58s	remaining: 9.4s
134:	learn: 0.3709546	total: 7.64s	remaining: 9.34s
135:	learn: 0.3709434	total: 7.68s	remaining: 9.27s
136:	learn: 0.3709308	total: 7.73s	remaining: 9.2s
137:	learn: 0.3709241	total: 7.78s	remaining: 9.13s
138:	learn: 0.3709172	total: 7.83s	remaining: 9.07s
139:	learn: 0.3708916	total: 7.88s	remaining: 9.01s
140:	learn: 0.3708715	total: 7.93s	remaining: 8.94s
141:	learn: 0.3708197	total: 7.98s	remaining: 8.88s
142:	learn: 0.3708073	total: 8.03s	remaining: 8.81s
143:	learn: 0.3707931	total: 8.07s	remaining: 8.74s
144:	learn: 0.3707875	total: 8.12s	remaining: 8.68s
145:	learn: 0.3707195	total: 8.17s	remaining: 8.62s
146:	learn: 0.3707133	total: 8.23s	remaining: 8.57s
147:	learn: 0.3706290	total: 8.29s	remaining: 8.51s
148:	learn: 0.3705265	total: 8.34s	remaining: 8.45s
149:	learn: 0.3705150	total: 8.39s	remaining: 8.39s
150:	learn: 0.3704699	total: 8.44s	remaining: 8.33s
151:	learn: 0.3704595	total: 8.49s	remaining: 8.27s
152:	learn: 0.3704457	total: 8.54s	remaining: 8.2s
153:	learn: 0.3704090	total: 8.58s	remaining: 8.13s
154:	learn: 0.3703708	total: 8.63s	remaining: 8.07s
155:	learn: 0.3703452	total: 8.67s	remaining: 8.01s
156:	learn: 0.3703380	total: 8.72s	remaining: 7.94s
157:	learn: 0.3703316	total: 8.77s	remaining: 7.88s
158:	learn: 0.3703208	total: 8.83s	remaining: 7.83s
159:	learn: 0.3703144	total: 8.88s	remaining: 7.77s
160:	learn: 0.3703029	total: 8.94s	remaining: 7.71s
161:	learn: 0.3702953	total: 8.99s	remaining: 7.65s
162:	learn: 0.3702782	total: 9.04s	remaining: 7.6s
163:	learn: 0.3702691	total: 9.1s	remaining: 7.55s
164:	learn: 0.3702576	total: 9.15s	remaining: 7.49s
165:	learn: 0.3702514	total: 9.2s	remaining: 7.43s
166:	learn: 0.3702425	total: 9.26s	remaining: 7.37s
167:	learn: 0.3702325	total: 9.31s	remaining: 7.31s
168:	learn: 0.3702100	total: 9.35s	remaining: 7.25s
169:	learn: 0.3702007	total: 9.4s	remaining: 7.19s
170:	learn: 0.3701953	total: 9.44s	remaining: 7.12s
171:	learn: 0.3701842	total: 9.5s	remaining: 7.07s
172:	learn: 0.3701797	total: 9.54s	remaining: 7s
173:	learn: 0.3701718	total: 9.6s	remaining: 6.95s
174:	learn: 0.3701555	total: 9.64s	remaining: 6.89s
175:	learn: 0.3700700	total: 9.7s	remaining: 6.83s
176:	learn: 0.3700628	total: 9.75s	remaining: 6.77s
177:	learn: 0.3700507	total: 9.8s	remaining: 6.72s
178:	learn: 0.3700451	total: 9.86s	remaining: 6.67s
179:	learn: 0.3699895	total: 9.91s	remaining: 6.61s
180:	learn: 0.3699765	total: 9.96s	remaining: 6.55s
181:	learn: 0.3698810	total: 10s	remaining: 6.49s
182:	learn: 0.3698491	total: 10.1s	remaining: 6.44s
183:	learn: 0.3698272	total: 10.1s	remaining: 6.38s
184:	learn: 0.3697690	total: 10.2s	remaining: 6.33s
185:	learn: 0.3697598	total: 10.2s	remaining: 6.28s
186:	learn: 0.3697189	total: 10.3s	remaining: 6.21s
187:	learn: 0.3697141	total: 10.3s	remaining: 6.15s
188:	learn: 0.3696300	total: 10.4s	remaining: 6.1s
189:	learn: 0.3695979	total: 10.4s	remaining: 6.05s
190:	learn: 0.3695903	total: 10.5s	remaining: 5.99s
191:	learn: 0.3695839	total: 10.6s	remaining: 5.93s
192:	learn: 0.3695695	total: 10.6s	remaining: 5.88s
193:	learn: 0.3695192	total: 10.7s	remaining: 5.83s
194:	learn: 0.3695142	total: 10.7s	remaining: 5.77s
195:	learn: 0.3695082	total: 10.8s	remaining: 5.72s
196:	learn: 0.3694953	total: 10.8s	remaining: 5.66s
197:	learn: 0.3694811	total: 10.9s	remaining: 5.61s
198:	learn: 0.3694769	total: 10.9s	remaining: 5.55s
199:	learn: 0.3694708	total: 11s	remaining: 5.49s
200:	learn: 0.3694499	total: 11s	remaining: 5.43s
201:	learn: 0.3693993	total: 11.1s	remaining: 5.38s
202:	learn: 0.3693849	total: 11.1s	remaining: 5.32s
203:	learn: 0.3693780	total: 11.2s	remaining: 5.26s
204:	learn: 0.3693733	total: 11.2s	remaining: 5.21s
205:	learn: 0.3693501	total: 11.3s	remaining: 5.15s
206:	learn: 0.3693334	total: 11.3s	remaining: 5.09s
207:	learn: 0.3693147	total: 11.4s	remaining: 5.03s
208:	learn: 0.3693069	total: 11.4s	remaining: 4.97s
209:	learn: 0.3693009	total: 11.5s	remaining: 4.92s
210:	learn: 0.3692934	total: 11.5s	remaining: 4.86s
211:	learn: 0.3692875	total: 11.6s	remaining: 4.8s
212:	learn: 0.3692630	total: 11.6s	remaining: 4.74s
213:	learn: 0.3692596	total: 11.7s	remaining: 4.68s
214:	learn: 0.3692450	total: 11.7s	remaining: 4.62s
215:	learn: 0.3692164	total: 11.7s	remaining: 4.57s
216:	learn: 0.3692090	total: 11.8s	remaining: 4.51s
217:	learn: 0.3692009	total: 11.8s	remaining: 4.45s
218:	learn: 0.3691942	total: 11.9s	remaining: 4.39s
219:	learn: 0.3691893	total: 11.9s	remaining: 4.33s
220:	learn: 0.3691689	total: 12s	remaining: 4.28s
221:	learn: 0.3691513	total: 12s	remaining: 4.22s
222:	learn: 0.3691334	total: 12.1s	remaining: 4.17s
223:	learn: 0.3691235	total: 12.1s	remaining: 4.11s
224:	learn: 0.3691178	total: 12.2s	remaining: 4.05s
225:	learn: 0.3690741	total: 12.2s	remaining: 4s
226:	learn: 0.3690622	total: 12.2s	remaining: 3.94s
227:	learn: 0.3690552	total: 12.3s	remaining: 3.88s
228:	learn: 0.3690488	total: 12.3s	remaining: 3.83s
229:	learn: 0.3690420	total: 12.4s	remaining: 3.77s
230:	learn: 0.3690308	total: 12.4s	remaining: 3.71s
231:	learn: 0.3689908	total: 12.5s	remaining: 3.66s
232:	learn: 0.3689848	total: 12.5s	remaining: 3.6s
233:	learn: 0.3689667	total: 12.6s	remaining: 3.55s
234:	learn: 0.3689581	total: 12.6s	remaining: 3.49s
235:	learn: 0.3688917	total: 12.7s	remaining: 3.44s
236:	learn: 0.3688768	total: 12.7s	remaining: 3.38s
237:	learn: 0.3688608	total: 12.8s	remaining: 3.33s
238:	learn: 0.3688572	total: 12.8s	remaining: 3.27s
239:	learn: 0.3688530	total: 12.9s	remaining: 3.22s
240:	learn: 0.3688443	total: 12.9s	remaining: 3.16s
241:	learn: 0.3688401	total: 13s	remaining: 3.11s
242:	learn: 0.3688316	total: 13s	remaining: 3.05s
243:	learn: 0.3688246	total: 13.1s	remaining: 3s
244:	learn: 0.3688108	total: 13.1s	remaining: 2.94s
245:	learn: 0.3687996	total: 13.2s	remaining: 2.89s
246:	learn: 0.3687963	total: 13.2s	remaining: 2.83s
247:	learn: 0.3687918	total: 13.3s	remaining: 2.78s
248:	learn: 0.3686916	total: 13.3s	remaining: 2.73s
249:	learn: 0.3686858	total: 13.4s	remaining: 2.67s
250:	learn: 0.3686793	total: 13.4s	remaining: 2.62s
251:	learn: 0.3686707	total: 13.4s	remaining: 2.56s
252:	learn: 0.3686645	total: 13.5s	remaining: 2.51s
253:	learn: 0.3686495	total: 13.5s	remaining: 2.45s
254:	learn: 0.3686451	total: 13.6s	remaining: 2.4s
255:	learn: 0.3686335	total: 13.6s	remaining: 2.34s
256:	learn: 0.3686277	total: 13.7s	remaining: 2.29s
257:	learn: 0.3686156	total: 13.7s	remaining: 2.23s
258:	learn: 0.3686104	total: 13.8s	remaining: 2.18s
259:	learn: 0.3685940	total: 13.8s	remaining: 2.13s
260:	learn: 0.3685830	total: 13.9s	remaining: 2.07s
261:	learn: 0.3685764	total: 13.9s	remaining: 2.02s
262:	learn: 0.3685657	total: 14s	remaining: 1.97s
263:	learn: 0.3685085	total: 14s	remaining: 1.91s
264:	learn: 0.3685031	total: 14.1s	remaining: 1.86s
265:	learn: 0.3684910	total: 14.1s	remaining: 1.8s
266:	learn: 0.3684867	total: 14.2s	remaining: 1.75s
267:	learn: 0.3684715	total: 14.2s	remaining: 1.7s
268:	learn: 0.3684438	total: 14.3s	remaining: 1.64s
269:	learn: 0.3683951	total: 14.3s	remaining: 1.59s
270:	learn: 0.3683687	total: 14.3s	remaining: 1.53s
271:	learn: 0.3683606	total: 14.4s	remaining: 1.48s
272:	learn: 0.3683543	total: 14.4s	remaining: 1.43s
273:	learn: 0.3683439	total: 14.5s	remaining: 1.37s
274:	learn: 0.3683326	total: 14.5s	remaining: 1.32s
275:	learn: 0.3683203	total: 14.6s	remaining: 1.26s
276:	learn: 0.3682565	total: 14.6s	remaining: 1.21s
277:	learn: 0.3682209	total: 14.6s	remaining: 1.16s
278:	learn: 0.3682068	total: 14.7s	remaining: 1.1s
279:	learn: 0.3681991	total: 14.7s	remaining: 1.05s
280:	learn: 0.3681451	total: 14.8s	remaining: 999ms
281:	learn: 0.3681377	total: 14.8s	remaining: 945ms
282:	learn: 0.3681220	total: 14.8s	remaining: 892ms
283:	learn: 0.3681169	total: 14.9s	remaining: 839ms
284:	learn: 0.3681013	total: 14.9s	remaining: 786ms
285:	learn: 0.3680781	total: 15s	remaining: 734ms
286:	learn: 0.3680675	total: 15s	remaining: 681ms
287:	learn: 0.3680588	total: 15.1s	remaining: 628ms
288:	learn: 0.3680458	total: 15.1s	remaining: 575ms
289:	learn: 0.3680377	total: 15.2s	remaining: 523ms
290:	learn: 0.3680287	total: 15.2s	remaining: 470ms
291:	learn: 0.3680227	total: 15.2s	remaining: 417ms
292:	learn: 0.3680089	total: 15.3s	remaining: 365ms
293:	learn: 0.3679743	total: 15.3s	remaining: 313ms
294:	learn: 0.3679434	total: 15.4s	remaining: 260ms
295:	learn: 0.3679331	total: 15.4s	remaining: 208ms
296:	learn: 0.3679240	total: 15.4s	remaining: 156ms
297:	learn: 0.3679172	total: 15.5s	remaining: 104ms
298:	learn: 0.3678874	total: 15.5s	remaining: 51.9ms
299:	learn: 0.3678744	total: 15.6s	remaining: 0us
0:	learn: 0.6579860	total: 51.7ms	remaining: 15.5s
1:	learn: 0.6272820	total: 100ms	remaining: 14.9s
2:	learn: 0.6015758	total: 147ms	remaining: 14.6s
3:	learn: 0.5776676	total: 192ms	remaining: 14.2s
4:	learn: 0.5557716	total: 242ms	remaining: 14.3s
5:	learn: 0.5368386	total: 292ms	remaining: 14.3s
6:	learn: 0.5201694	total: 344ms	remaining: 14.4s
7:	learn: 0.5055487	total: 396ms	remaining: 14.5s
8:	learn: 0.4922437	total: 451ms	remaining: 14.6s
9:	learn: 0.4805079	total: 507ms	remaining: 14.7s
10:	learn: 0.4700964	total: 560ms	remaining: 14.7s
11:	learn: 0.4609816	total: 607ms	remaining: 14.6s
12:	learn: 0.4526444	total: 652ms	remaining: 14.4s
13:	learn: 0.4451981	total: 698ms	remaining: 14.3s
14:	learn: 0.4386487	total: 750ms	remaining: 14.3s
15:	learn: 0.4330889	total: 805ms	remaining: 14.3s
16:	learn: 0.4278893	total: 855ms	remaining: 14.2s
17:	learn: 0.4227463	total: 905ms	remaining: 14.2s
18:	learn: 0.4173433	total: 961ms	remaining: 14.2s
19:	learn: 0.4134646	total: 1.01s	remaining: 14.2s
20:	learn: 0.4105287	total: 1.07s	remaining: 14.2s
21:	learn: 0.4072954	total: 1.12s	remaining: 14.2s
22:	learn: 0.4045300	total: 1.18s	remaining: 14.2s
23:	learn: 0.4023882	total: 1.24s	remaining: 14.2s
24:	learn: 0.4001035	total: 1.29s	remaining: 14.2s
25:	learn: 0.3982952	total: 1.35s	remaining: 14.2s
26:	learn: 0.3966556	total: 1.4s	remaining: 14.1s
27:	learn: 0.3951757	total: 1.45s	remaining: 14.1s
28:	learn: 0.3930501	total: 1.51s	remaining: 14.1s
29:	learn: 0.3919589	total: 1.56s	remaining: 14s
30:	learn: 0.3905641	total: 1.63s	remaining: 14.1s
31:	learn: 0.3896501	total: 1.67s	remaining: 14s
32:	learn: 0.3879859	total: 1.72s	remaining: 13.9s
33:	learn: 0.3869183	total: 1.77s	remaining: 13.8s
34:	learn: 0.3862207	total: 1.81s	remaining: 13.7s
35:	learn: 0.3855259	total: 1.94s	remaining: 14.2s
36:	learn: 0.3847300	total: 2.03s	remaining: 14.4s
37:	learn: 0.3841263	total: 2.1s	remaining: 14.5s
38:	learn: 0.3831636	total: 2.17s	remaining: 14.5s
39:	learn: 0.3827523	total: 2.24s	remaining: 14.6s
40:	learn: 0.3823488	total: 2.3s	remaining: 14.5s
41:	learn: 0.3816643	total: 2.35s	remaining: 14.4s
42:	learn: 0.3808669	total: 2.39s	remaining: 14.3s
43:	learn: 0.3804775	total: 2.43s	remaining: 14.1s
44:	learn: 0.3801611	total: 2.47s	remaining: 14s
45:	learn: 0.3796714	total: 2.51s	remaining: 13.9s
46:	learn: 0.3793473	total: 2.55s	remaining: 13.7s
47:	learn: 0.3788947	total: 2.59s	remaining: 13.6s
48:	learn: 0.3787604	total: 2.63s	remaining: 13.5s
49:	learn: 0.3785021	total: 2.67s	remaining: 13.4s
50:	learn: 0.3783350	total: 2.72s	remaining: 13.3s
51:	learn: 0.3781505	total: 2.76s	remaining: 13.2s
52:	learn: 0.3779250	total: 2.81s	remaining: 13.1s
53:	learn: 0.3775276	total: 2.85s	remaining: 13s
54:	learn: 0.3774001	total: 2.89s	remaining: 12.9s
55:	learn: 0.3772622	total: 2.94s	remaining: 12.8s
56:	learn: 0.3771272	total: 2.98s	remaining: 12.7s
57:	learn: 0.3770279	total: 3.01s	remaining: 12.6s
58:	learn: 0.3769307	total: 3.05s	remaining: 12.4s
59:	learn: 0.3766124	total: 3.09s	remaining: 12.3s
60:	learn: 0.3765220	total: 3.13s	remaining: 12.3s
61:	learn: 0.3764296	total: 3.17s	remaining: 12.1s
62:	learn: 0.3760083	total: 3.21s	remaining: 12.1s
63:	learn: 0.3759270	total: 3.25s	remaining: 12s
64:	learn: 0.3758222	total: 3.29s	remaining: 11.9s
65:	learn: 0.3753668	total: 3.34s	remaining: 11.8s
66:	learn: 0.3753240	total: 3.38s	remaining: 11.8s
67:	learn: 0.3752774	total: 3.42s	remaining: 11.7s
68:	learn: 0.3752152	total: 3.47s	remaining: 11.6s
69:	learn: 0.3751519	total: 3.51s	remaining: 11.5s
70:	learn: 0.3747923	total: 3.55s	remaining: 11.5s
71:	learn: 0.3747484	total: 3.59s	remaining: 11.4s
72:	learn: 0.3747074	total: 3.63s	remaining: 11.3s
73:	learn: 0.3746725	total: 3.68s	remaining: 11.2s
74:	learn: 0.3743923	total: 3.72s	remaining: 11.2s
75:	learn: 0.3743639	total: 3.76s	remaining: 11.1s
76:	learn: 0.3742819	total: 3.8s	remaining: 11s
77:	learn: 0.3740884	total: 3.84s	remaining: 10.9s
78:	learn: 0.3739438	total: 3.88s	remaining: 10.9s
79:	learn: 0.3739293	total: 3.92s	remaining: 10.8s
80:	learn: 0.3738796	total: 3.96s	remaining: 10.7s
81:	learn: 0.3737427	total: 4s	remaining: 10.6s
82:	learn: 0.3737161	total: 4.04s	remaining: 10.6s
83:	learn: 0.3736899	total: 4.08s	remaining: 10.5s
84:	learn: 0.3736616	total: 4.12s	remaining: 10.4s
85:	learn: 0.3735377	total: 4.17s	remaining: 10.4s
86:	learn: 0.3735132	total: 4.2s	remaining: 10.3s
87:	learn: 0.3734855	total: 4.25s	remaining: 10.2s
88:	learn: 0.3734198	total: 4.29s	remaining: 10.2s

RandomizedSearchCV(cv=2,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(remainder='passthrough',
                                                                transformers=[('ohe',
                                                                               OneHotEncoder(handle_unknown='ignore'),
                                                                               ['gender',
                                                                                'exp_group',
                                                                                'os',
                                                                                'source',
                                                                                'topic']),
                                                                              ('mte',
                                                                               MEstimateEncoder(cols=['country',
                                                                                                      'city'],
                                                                                                m=10.0),
                                                                               ['country',
                                                                                'city'])])),
                                             ('model',
                                              <catboost.core.CatBoostClassifier object at 0x0000025F30F682C0>)]),
                   n_iter=15, n_jobs=1,
                   param_distributions={'model__bagging_temperature': [0.5,
                                                                       1.0],
                                        'model__depth': [4, 6, 8, 10],
                                        'model__l2_leaf_reg': [3, 10, 30],
                                        'model__learning_rate': [0.01, 0.03,
                                                                 0.05, 0.1],
                                        'model__random_strength': [1, 3]},
                   random_state=42, scoring='roc_auc', verbose=1)

In [19]:
print(search.best_params_) 
print(search.best_score_)

{'model__random_strength': 1, 'model__learning_rate': 0.03, 'model__l2_leaf_reg': 30, 'model__depth': 8, 'model__bagging_temperature': 0.5}
0.6944604693021335

In [20]:
best_pipe = search.best_estimator_

with open('model.pkl', 'wb') as f:
    pickle.dump(best_pipe, f)

In [ ]:
df_posts = df_posts.drop(columns=['text'])
df_users_prof.to_pickle("user_features.pkl")
df_posts.to_pickle("post_features.pkl")

In [ ]:
#conn_str = "postgresql://robot-startml-ro:pheiph0hahj1Vaif@postgres.lab.karpov.courses:6432/startml"

#df_users_prof.to_sql(
#    conn_str,  
#    if_exists="replace",  
#    index=False,  
#    method="multi", 
#)


#df_posts.to_sql(
#    "ilya_budretskiy_post_features",  
#    conn_str, +
#    if_exists="replace",  
#    index=False,  
#    method="multi", 
#)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdd in position 72: invalid continuation byte